version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: 
         name : Docker Login and cek images
         command : |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker run -d --name db baihaki/hellodocker:ujiversion
          docker images
     - run :
         name : Docker build and push
         command : |
          docker tag baihaki/hellodocker:ujiversion baihaki/hellodocker:${CIRCLE_SHA1}
          docker images
          docker push baihaki/hellodocker:${CIRCLE_SHA1}
