version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         docker run -d --name db baihaki/hellodocker:ujiversion

     # build the application image
     - run: docker build -t baihaki/hellodocker:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push baihaki/hellodocker:$CIRCLE_BRANCH