version: 2
jobs:
 build:
   working_directory: ~/tmp
   docker:
     - image : circle/node:7
   steps:
     - checkout
     - run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         docker run -d --name db baihaki/hellodocker:ujiversion

     # build the application image
     #- run: docker build -t baihaki/hellodocker:$CIRCLE_BRANCH .

     # deploy the image
     #- run: docker push baihaki/hellodocker:$CIRCLE_BRANCH